name: Install & Build
description: Install all dependencies and builds the app

runs:
  using: composite
  steps:
    - shell: bash
      run: | # shell
        bun install --frozen-lockfile
        bun run build
