import { assertStrictEquals } from 'jsr:@std/assert'
import z from 'zod'
import { Data, DataSchema, targetEquals } from '@targetd/api'

Deno.test('type stress: 100 payloads + 30 targeting descriptors', async () => {
  const data = await Data.create(
    DataSchema.create()
      .usePayload({ payload_0: z.string() })
      .usePayload({ payload_1: z.string() })
      .usePayload({ payload_2: z.string() })
      .usePayload({ payload_3: z.string() })
      .usePayload({ payload_4: z.string() })
      .usePayload({ payload_5: z.string() })
      .usePayload({ payload_6: z.string() })
      .usePayload({ payload_7: z.string() })
      .usePayload({ payload_8: z.string() })
      .usePayload({ payload_9: z.string() })
      .usePayload({ payload_10: z.string() })
      .usePayload({ payload_11: z.string() })
      .usePayload({ payload_12: z.string() })
      .usePayload({ payload_13: z.string() })
      .usePayload({ payload_14: z.string() })
      .usePayload({ payload_15: z.string() })
      .usePayload({ payload_16: z.string() })
      .usePayload({ payload_17: z.string() })
      .usePayload({ payload_18: z.string() })
      .usePayload({ payload_19: z.string() })
      .usePayload({ payload_20: z.string() })
      .usePayload({ payload_21: z.string() })
      .usePayload({ payload_22: z.string() })
      .usePayload({ payload_23: z.string() })
      .usePayload({ payload_24: z.string() })
      .usePayload({ payload_25: z.string() })
      .usePayload({ payload_26: z.string() })
      .usePayload({ payload_27: z.string() })
      .usePayload({ payload_28: z.string() })
      .usePayload({ payload_29: z.string() })
      .usePayload({ payload_30: z.string() })
      .usePayload({ payload_31: z.string() })
      .usePayload({ payload_32: z.string() })
      .usePayload({ payload_33: z.string() })
      .usePayload({ payload_34: z.string() })
      .usePayload({ payload_35: z.string() })
      .usePayload({ payload_36: z.string() })
      .usePayload({ payload_37: z.string() })
      .usePayload({ payload_38: z.string() })
      .usePayload({ payload_39: z.string() })
      .usePayload({ payload_40: z.string() })
      .usePayload({ payload_41: z.string() })
      .usePayload({ payload_42: z.string() })
      .usePayload({ payload_43: z.string() })
      .usePayload({ payload_44: z.string() })
      .usePayload({ payload_45: z.string() })
      .usePayload({ payload_46: z.string() })
      .usePayload({ payload_47: z.string() })
      .usePayload({ payload_48: z.string() })
      .usePayload({ payload_49: z.string() })
      .usePayload({ payload_50: z.string() })
      .usePayload({ payload_51: z.string() })
      .usePayload({ payload_52: z.string() })
      .usePayload({ payload_53: z.string() })
      .usePayload({ payload_54: z.string() })
      .usePayload({ payload_55: z.string() })
      .usePayload({ payload_56: z.string() })
      .usePayload({ payload_57: z.string() })
      .usePayload({ payload_58: z.string() })
      .usePayload({ payload_59: z.string() })
      .usePayload({ payload_60: z.string() })
      .usePayload({ payload_61: z.string() })
      .usePayload({ payload_62: z.string() })
      .usePayload({ payload_63: z.string() })
      .usePayload({ payload_64: z.string() })
      .usePayload({ payload_65: z.string() })
      .usePayload({ payload_66: z.string() })
      .usePayload({ payload_67: z.string() })
      .usePayload({ payload_68: z.string() })
      .usePayload({ payload_69: z.string() })
      .usePayload({ payload_70: z.string() })
      .usePayload({ payload_71: z.string() })
      .usePayload({ payload_72: z.string() })
      .usePayload({ payload_73: z.string() })
      .usePayload({ payload_74: z.string() })
      .usePayload({ payload_75: z.string() })
      .usePayload({ payload_76: z.string() })
      .usePayload({ payload_77: z.string() })
      .usePayload({ payload_78: z.string() })
      .usePayload({ payload_79: z.string() })
      .usePayload({ payload_80: z.string() })
      .usePayload({ payload_81: z.string() })
      .usePayload({ payload_82: z.string() })
      .usePayload({ payload_83: z.string() })
      .usePayload({ payload_84: z.string() })
      .usePayload({ payload_85: z.string() })
      .usePayload({ payload_86: z.string() })
      .usePayload({ payload_87: z.string() })
      .usePayload({ payload_88: z.string() })
      .usePayload({ payload_89: z.string() })
      .usePayload({ payload_90: z.string() })
      .usePayload({ payload_91: z.string() })
      .usePayload({ payload_92: z.string() })
      .usePayload({ payload_93: z.string() })
      .usePayload({ payload_94: z.string() })
      .usePayload({ payload_95: z.string() })
      .usePayload({ payload_96: z.string() })
      .usePayload({ payload_97: z.string() })
      .usePayload({ payload_98: z.string() })
      .usePayload({ payload_99: z.string() })
      .useTargeting({ target_0: targetEquals(z.string()) })
      .useTargeting({ target_1: targetEquals(z.string()) })
      .useTargeting({ target_2: targetEquals(z.string()) })
      .useTargeting({ target_3: targetEquals(z.string()) })
      .useTargeting({ target_4: targetEquals(z.string()) })
      .useTargeting({ target_5: targetEquals(z.string()) })
      .useTargeting({ target_6: targetEquals(z.string()) })
      .useTargeting({ target_7: targetEquals(z.string()) })
      .useTargeting({ target_8: targetEquals(z.string()) })
      .useTargeting({ target_9: targetEquals(z.string()) })
      .useTargeting({ target_10: targetEquals(z.string()) })
      .useTargeting({ target_11: targetEquals(z.string()) })
      .useTargeting({ target_12: targetEquals(z.string()) })
      .useTargeting({ target_13: targetEquals(z.string()) })
      .useTargeting({ target_14: targetEquals(z.string()) })
      .useTargeting({ target_15: targetEquals(z.string()) })
      .useTargeting({ target_16: targetEquals(z.string()) })
      .useTargeting({ target_17: targetEquals(z.string()) })
      .useTargeting({ target_18: targetEquals(z.string()) })
      .useTargeting({ target_19: targetEquals(z.string()) })
      .useTargeting({ target_20: targetEquals(z.string()) })
      .useTargeting({ target_21: targetEquals(z.string()) })
      .useTargeting({ target_22: targetEquals(z.string()) })
      .useTargeting({ target_23: targetEquals(z.string()) })
      .useTargeting({ target_24: targetEquals(z.string()) })
      .useTargeting({ target_25: targetEquals(z.string()) })
      .useTargeting({ target_26: targetEquals(z.string()) })
      .useTargeting({ target_27: targetEquals(z.string()) })
      .useTargeting({ target_28: targetEquals(z.string()) })
      .useTargeting({ target_29: targetEquals(z.string()) })
      .build(),
  )
    .addRules('payload_0', [{ payload: 'hello' }])
    .addRules('payload_99', [{ payload: 'world' }])

  assertStrictEquals(await data.getPayload('payload_0'), 'hello')
  assertStrictEquals(await data.getPayload('payload_99'), 'world')
  assertStrictEquals(await data.getPayload('payload_50'), undefined)

  const query = { target_0: 'a', target_15: 'b', target_29: 'c' }
  assertStrictEquals(await data.getPayload('payload_0', query), 'hello')
})
