name: Deno Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1' # Weekly on Mondays
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version-file: .dvmrc
      - uses: johngeorgewright/workflows/actions/deno-update@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-labels: dependencies
          recursive: 'true'
          version-policy: latest
