name: Release

on:
  push:
    branches: [master]

jobs:
  release-github:
    name: Github Release
    runs-on: ubuntu-latest
    concurrency:
      group: release
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PUSH_TOKEN }}

  release-jsr:
    needs: [release-github]
    if: needs.release-github.outputs.releases_created == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path_released: ${{ fromJson(needs.release-github.outputs.paths_released) }}
    name: Publish ${{ matrix.path_released }} to JSR
    container:
      image: oven/bun:1
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - id: package
        run: echo "private=$(cat package.json | jq -r '.private // false')" >> $GITHUB_OUTPUT
      - if: steps.package.outputs.private != 'true'
        uses: ./.github/actions/test
      - if: steps.package.outputs.private != 'true'
        working-directory: ${{ matrix.path_released }}
        run: | # shell
          bun pm pack --filename=$(pwd)/temp.tgz
          tar -xOf temp.tgz package/package.json > package.json
          rm -rf package temp.tgz
          bunx jsr publish
