name: Release

on:
  push:
    branches: [master]

jobs:
  release-github:
    name: Github Release
    runs-on: ubuntu-latest
    concurrency:
      group: release-github
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PUSH_TOKEN }}

  release-test:
    needs: [release-github]
    if: needs.release-github.outputs.releases_created == 'true'
    runs-on: ubuntu-latest
    container:
      image: oven/bun:1
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/test

  release-npm:
    needs: [release-github, release-test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path_released: ${{ fromJson(needs.release-github.outputs.paths_released) }}
    name: Publish ${{ matrix.path_released }} to NPM
    environment: npm
    concurrency: release-npm
    container:
      image: oven/bun:1
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - working-directory: ${{ matrix.path_released }}
        run: npm publish
