name: Release

on:
  push:
    branches: [master]

jobs:
  release-github:
    name: Github Release
    runs-on: ubuntu-latest
    concurrency:
      group: release
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PEM }}
          permission-contents: write
          permission-issues: write
          permission-pull-requests: write
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}

  release-jsr:
    needs: [release-github]
    if: needs.release-github.outputs.releases_created == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path_released: ${{ fromJson(needs.release-github.outputs.paths_released) }}
    name: Publish ${{ matrix.path_released }} to JSR
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version-file: .dvmrc
      - uses: ./.github/actions/test
      - working-directory: ${{ matrix.path_released }}
        run: if [ "$(cat deno.json | jq -r '.private // false')" != "true" ]; then deno
          publish; fi
